# Generated by Django 5.2.7 on 2025-11-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
